### ISSUE TITLE
0.6 update does not recognize my 3rd door 

### ISSUE THREAD

**Issue by rtorchia** [pauln/tailwind-home-assistant#27] opened 2023-12-26 13:21 UTC
Did the update to 0.6 and now my third garage door is unavailable in home assistant, stating  "This entity is no longer being provided by the tailwind_iq3 integration"

**Comment by pauln** [comment] 2023-12-27 04:33
Thanks for your PRs on `aiotailwind` - looks like the number of doors reported by the device _isn't_ the number configured in the app, unfortunately, and as a result of that and my rusty Python knowledge, I made a bad assumption about the array slicing.  I've merged those PRs, but something seems to have gone wrong with my test HA instance, so I haven't tested an update to the integration yet; I'll do that later and release a new version once I can confirm that it's all working as expected.

**Comment by pauln** [comment] 2023-12-27 09:16
Rebuilding the dev container seems to have fixed the issue I was having with it (any attempt to open the test HA instance caused the browser to use all available RAM and then crash - very odd issue that I haven't seen before), so I've now confirmed that it works as expected and released v0.6.1 (which just bumps the `aiotailwind` requirement to the new version).

Thanks again for your report and PRs.

**Closed by pauln** 2023-12-27 09:16 UTC

**Comment by rtorchia** [comment] 2023-12-27 12:42
Just updated, and also updated to HA 2023.12.4, and everything looks good!

**Comment by pauln** [comment] 2024-01-03 21:38
Interestingly, HA 2024.1 has just been released - and includes a core Tailwind integration (unrelated to this custom integration - it would've been nice to know they were working on it; I'd have happily contributed and/or helped test it).  The core integration requires firmware v10.10, which has also just been released (check the Tailwind app to see if it's offering the update or has already auto-updated) - which notably fixes the `door_num` issue, so it now reports the configured number of doors rather than always reporting the maximum number (i.e. 3).

**Comment by rtorchia** [comment] 2024-01-03 21:42
I just read that the integration for Tailwind was placed into HA 2024.1, and assumed it was your code that was integrated! I may look at the HA code and see how it differs from your code.
And thanks for the heads up on the firmware update for Tailwind!

**Comment by pauln** [comment] 2024-01-04 01:47
I was planning to submit the integration to HA core, now that I finally got around to moving to the JSON API and splitting that out into a separate library - but I guess that's no longer needed.  Ah well - it's good to have a Tailwind integration in HA core, one way or another.  I haven't had a chance to look at the core integration in any detail yet, but I'll most likely archive/deprecate this project (some time soon) and put any further development effort into improving the core integration and its underlying library - better to unify efforts, rather than have two parallel projects.
